# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Restaurant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwipeableTabBarController'
  pod 'SwiftLint'
  pod 'JNSegmentedControl', '~> 1.0'
  pod 'FoldingCell', '~> 5.0'
  pod "MIBadgeButton-Swift", :git => 'https://github.com/mustafaibrahim989/MIBadgeButton-Swift.git', :branch => 'master'
	pod 'Alamofire', '~> 4.3'
  
  


end
